name: Build and push static pages

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Pages
        id: pages
        uses: actions/configure-pages@v3

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3
          bundler-cache: true

      - name: Build site
        run: bundle exec jekyll build
        env:
          JEKYLL_ENV: "production"

      - run: git config user.name github-actions
      - run: git config user.email github-actions@github.com
      - run: git --work-tree _site add --all
      - run: git commit -m "Automatic deployment by github-actions"
      - run: git push origin HEAD:static-pages --force
